services:
  mongo:
    image: mongo
    restart: always
    container_name: carServiceMongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db # Persist MongoDB data

volumes:
  mongo-data:
    driver: local